django/trydjango1-11/src/menus/urls.py
from django.conf.urls import url


from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView,
)

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'$', ItemListView.as_view(), name='list'),
]

django/trydjango1-11/src/profiles/urls.py
from django.conf.urls import url
from .views import ProfileDetailView


urlpatterns = [
    url(r'^(?P<username>[\w-]+)/$', ProfileDetailView.as_view(), name='detail'),
]

django/trydjango1-11/src/menus/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse


from restaurants.models import Restaurant


class Item(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant = models.ForeignKey(Restaurant)

    name = models.CharField(max_length=120)
    contents = models.TextField(help_text='Seperate each item by comma')
    excludes = models.TextField(blank=True, null=True, help_text='Seperate each item by comma')
    public = models.BooleanField(default=True)

    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-updated', '-timestamp']

    def get_contents(self):
        return self.contents.split(',')

    def get_excludes(self):
        return self.excludes.split(',')

    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={'pk': self.pk})

django/trydjango1-11/src/profiles/models.py
from django.db import models

# Create your models here.

django/trydjango1-11/src/profiles/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404, Http404
from django.views.generic import DetailView

from restaurants.models import Restaurant
from menus.models import Item

User = get_user_model()


class ProfileDetailView(DetailView):
    template_name = 'profiles/user.html'

    def get_object(self, queryset=None):
        username = self.kwargs.get('username')
        if username is None:
            raise Http404
        return get_object_or_404(User, username__iexact=username, is_active=True)

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(*args, **kwargs)
        user = context['user']
        query = self.request.GET.get('q')
        items_exists = Item.objects.filter(user=user).exists()
        qs = Restaurant.objects.filter(owner=user).search(query)
        if items_exists and qs.exists():
            context['locations'] = qs
        return context

django/trydjango1-11/src/profiles/templates/profiles/user.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ user.username }}</h1>
    <form action="." class="form" method="GET">
        <input type="text" placeholder="Search" name="q" value="{{ request.GET.q }}">
        <button class="btn btn-default" type="submit">Search</button>
    </form>

    <hr>

    {% for restaurant in locations %}
        <div class="row">
            <div class="col-sm-12" style="border: 1px solid #ccc; border-radius: 5px; margin-bottom: 15px;">
                <h4>{{ restaurant.name }}</h4>
                <p>{{ restaurant.location }} | {{ restaurant.category }}</p>
                <div class="thumbnail">
                    <br>
                    <b>Items</b>
                    <ul>
                        {% for item in restaurant.item_set.all %}
                        <li style="margin-bottom: 15px">{{ item.name }}<br>
                            Contains : {{ item.contents }}
                            {% for ing in item.get_contents %}
                                <a href="{{ request.path }}?q={{ing}}">{{ ing }}</a>
                            {% endfor %}
                            </ul>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <hr>
    {% empty %}
        <p>no restaurants added yet.</p>
    {% endfor %}

{% endblock %}