django/trydjango1-11/src/menus/urls.py
from django.conf.urls import url


from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView,
)

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'$', ItemListView.as_view(), name='list'),
]

django/trydjango1-11/src/muypicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, PasswordResetView


urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^profiles/', include('profiles.urls'), name='profiles'),
    url(r'^password_reset/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
]

django/trydjango1-11/src/menus/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse


from restaurants.models import Restaurant


class Item(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant = models.ForeignKey(Restaurant)

    name = models.CharField(max_length=120)
    contents = models.TextField(help_text='Seperate each item by comma')
    excludes = models.TextField(blank=True, null=True, help_text='Seperate each item by comma')
    public = models.BooleanField(default=True)

    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-updated', '-timestamp']

    def get_contents(self):
        return self.contents.split(',')

    def get_excludes(self):
        return self.excludes.split(',')

    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={'pk': self.pk})

django/trydjango1-11/src/menus/forms.py
from django import forms

from restaurants.models import Restaurant

from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'restaurant',
            'name',
            'contents',
            'excludes',
            'public',
        ]

    def __init__(self, user=None, *args, **kwargs):
        print(user)
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['restaurant'].queryset = Restaurant.objects.filter(owner=user)

django/trydjango1-11/src/menus/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .models import Item
from .forms import ItemForm


class ItemListView(ListView):
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)


class ItemDetailView(DetailView):
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)


class ItemCreateView(LoginRequiredMixin, CreateView):
    template_name = 'form.html'
    form_class = ItemForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ItemCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(ItemCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Add Item'
        return context


class ItemUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'menus/detail-update.html'
    form_class = ItemForm

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Item'
        return context

    def get_form_kwargs(self):
        kwargs = super(ItemUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

django/trydjango1-11/src/menus/templates/menus/detail-update.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ form.instance.name }}</h1>
    <h2>Location: {{ form.instance.restaurant }}</h2>

        {% if form.instance.contents %}
            Contents
            <ul>
                {% for item in form.instance.get_contents %}
                    <li>{{ item }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if form.instance.excludes %}
            Excludes
            <ul>
                {% for item in object.get_excludes %}
                    <li>{{ item }}</li>
                {% endfor %}
            </ul>
        {% endif %}

    <hr>

    <h3>Make changes</h3>

    {% include 'snippets/form-snippet.html' with form=form %}

{% endblock %}

django/trydjango1-11/src/menus/templates/menus/item_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ object.name }}</h1>
    <h2>Location: {{ object.restaurant }}</h2>

        {% if object.contents %}
            Contents
            <ul>
                {% for item in object.get_contents %}
                    <li>{{ item }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if obj.excludes %}
            Excludes
            <ul>
                {% for item in object.get_excludes %}
                    <li>{{ item }}</li>
                {% endfor %}
            </ul>
        {% endif %}

{% endblock %}

django/trydjango1-11/src/menus/templates/menus/item_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Menu Items list <small><a href="{% url 'menus:create' %}">Add Item </a></small></h1>

    <ul>
        {% for item in object_list %}
            <li><a href="{{ item.get_absolute_url }}">{{ item.name }}</a>
                {% if obj.contents %}
                    Contents
                    <ul>
                        {% for item in obj.get_contents %}
                            <li>{{ item }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}

                {% if obj.excludes %}
                    Excludes
                    <ul>
                        {% for item in obj.get_excludes %}
                            <li>{{ item }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% empty %}
            <li><a href="{% url 'menus:create' %}">Add item</a></li>
        {% endfor %}
    </ul>
{% endblock %}